apiVersion: v1
kind: Pod
metadata:
  namespace: maninamespace
  name: podtoaccessfromconfigmap
spec:
  containers:
  - name: simple-web-app1
    image: nginx:latest
    ports:
      - containerPort: 8080
    env:
      - name: anykey
        valueFrom: 
          configMapKeyRef:
            name: dbconfigmap
            #this is the name of configmap object
            key: dbpassword
      - name: bookname
        value: docker&kubernetes
      - name: mobilename
        value: realme