apiVersion: v1
kind: Pod
metadata:
  namespace: maninamespace
  name: podtoaccessallvaluesfromconfigmap
spec:
  containers:
  - name: simple-web-app1
    image: nginx:latest
    ports:
      - containerPort: 8080
    envFrom:
    #we can get values from multiple maps,hence it is a list type,hence we used - symbol
      - configMapRef: 
          name: dbconfigmap
     