apiVersion: v1
kind: Pod
metadata:
  namespace: maninamespace
  name: podtoaccesssingleandallvaluesfromconfigmap
spec:
  containers:
  - name: simple-web-app1
    image: nginx:latest
    ports:
      - containerPort: 8080
    env:
      - name: databaseusername
        valueFrom:
          configMapKeyRef:
            name: dbconfigmap
            key: dbname
          
    envFrom:
    #we can get values from multiple maps,hence it is a list type,hence we used - symbol
      - configMapRef: 
          name: dbconfigmap
     