apiVersion: v1
kind: Pod
metadata:
  namespace: maninamespace
  name: podtofetchsinglesecret
spec:
  containers:
  - name: simple-web-app1
    image: nginx:latest
    ports:
      - containerPort: 8080
    env:
      - name: anykey
        valueFrom: 
#since we are accessing only 1 value from a key,hence we named as configMapKeyRef
          configMapKeyRef:
            name: dbconfigmap
            #this is the name of configmap object
            key: dbpassword #this is the key of that value
      - name: databasepassword
        valueFrom: 
          secretKeyRef:
            name: dbsecrets
            key: dbpassword
      - name: bookname
        value: docker&kubernetes
      - name: mobilename
        value: realme
      - name: note
        value: twothousand
    envFrom:
      - secretRef: 
          name: dbsecrets