apiVersion: v1
kind: Pod
metadata:
#it says name of this object
  name: charanpod
  #namespace tells in which namespace this object is going to reside
  namespace: charan
  labels:
  #label can be anything
    score: low
spec:
  containers:
  - image: stephengrider/multi-client
    name: manicontainer
    ports:
    #here port number means we should give port only where the software will run
    # if ur application is running on 8080, here u should give 80 only
      - containerPort: 3000