apiVersion: v1
kind: Pod
metadata:
  namespace: maninamespace
  name: lowsegmentpod
spec:
  containers:
  - image: nginx
    name: dataprocessor
    resources: 
      requests:
        memory: "256Mi"
        cpu: 5m
      limits:
        memory: "512Gi"
        cpu: 10m