apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplobj
  namespace: samsung
  # this is only label of the depl obj, can be diff from replicaset match label
  labels:
    brand: realme
spec:
  replicas: 3 
  selector:
  #this selector label must match with pod label, else rs will select another pod 
    matchLabels: 
      brand: samsung
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
    #here these labels are aplpied  to the pod or pod will be created with this label
      labels:
        brand: samsung
    spec:
      containers:
      - image: stephengrider/multi-worker
        name: stephencont
        ports:
        -  containerPort: 3001
      