apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplobj
  namespace: manins
  # this is only label of the depl obj, can be diff from replicaset match label
  labels:
    brand: realme
spec:
  replicas: 3 
  selector:
  #this selector label must match with pod label, else rs will select another pod 
    matchLabels: 
      brand: samsung
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
    #here these labels are aplpied  to the pod or pod will be created with this label
      labels:
        brand: samsung
    spec:
      containers:
      - image: stephengrider/multi-client
        name: stephencont
        ports:
        #this means originally also the application should run on 3000 port
        -  containerPort: 3000
---
#Service object creations
---
apiVersion: v1
kind: Service
metadata:
  name: manisvcobject
  namespace: manins
  labels:
    brand: realme
spec:
  type: NodePort
  ports:
  - targetPort: 3000 #it is the port to which the requests will be redirected from NodePort
    port: 3050 #i dont know what is this
  #inside a node machine, this service obj will be installed on the port number nodeport
    #NodePort is the port where this object is going to reside inside node machine
    nodePort: 31519
    #therefore if any request comes to node machines nodeport -all those traffic will be 
    # diverted to pod's targetPort
    
  selector:
#selector is the most important, this service object main pupose is to redirect the traffic to the pods, this service object will select and send the traffic to the pods with the below label
    brand: samsung
  
