apiVersion: apps/v1
kind: Deployment
#it will create object called Deployment 
#and since this is a wrapper around replicaset object it manages/picks replicaset with this label only
metadata:
  name: d1-depl-obj-name 
  labels:
#here it will select only those replicasets whose label is env:test
    env: test
spec:
#this will create a replica set and it will manage the pods whose label is env:test
  replicas: 3
  selector: 
#if u give selector means replicaset will select only those pods with label env:test
    matchLabels:
      env: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template: 
#template means this is code of pod creation
    metadata:
#metadata label means it will create the pod with the below labels env:test
      labels:
        env: test
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
    
  
  
    
    