FROM node:16-alpine
WORKDIR "/app"          -## it will set the current directory to app 
                            so that hereafter all the commands like RUN,CMD everything will 
                            run in this folder
COPY ./package.json ./    -## COPY <src-path> <destination-path>
                          -## it says copy the package.json from current directory to docker 
                          work directory here it is /app
                          here ./ means current working directory

RUN npm install
COPY . .
CMD ["npm", "run", "dev"]  -## when container starts this command will be executed

-##########sample -2
====================
FROM node:16-alpine as builder  -## here "builder" is a phase
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html  -## here from builder phase we are 
                                                    copying the output from folder "/app/build"
                                                    to destination folder "/usr/share/nginx/html"

