- name: playbook-to-install-nginx-server
  hosts: localhost
  tasks:
  - name: install nginx-server
    apt:
      name: nginx
      state: latest
  - name: start nginx server
    service:
      name: nginx
      state: started
  - name: install postgres
    apt:
      name: postgresql
      state: latest
  - name: start postgresql
    service: 
      name: postgresql
      state: started