---
- name: execting a playbook which have tasks to start servers
  hosts: localhost
  tasks:
  - name: task to stop ssh server
    service: 
      name: ssh
      state: stopped
  - name: task to start ssh server
    service: 
      name: ssh
      state: started